stages:
- compile
- release

Compile Linux:
 stage: compile
 script:
 - sudo pip3 install dnslib configparser IPy pyinstaller
 - /home/gitlab-runner/.local/bin/pyinstaller --onefile dnschef.py
 - mv dist/dnschef dnschef_linux.elf
 artifacts: 
  paths:
  - dnschef_linux.elf
  expire_in: 1 week

Release:
 stage: release
 script: 
 - mkdir -p bin/linux bin/windows
 - mv dnschef_linux.elf bin/linux/
 - mv /home/gitlab-runner/dnschef_windows.zip .
 - unzip dnschef_windows.zip -d bin/windows/
 when: manual
 artifacts: 
  paths: 
  - bin/
  - start.sh
  - start.bat
  - README.txt
  - LICENSE
  expire_in: 1 week


# How to compile on Windows: 
# - Download and install Python3
# - Install dependencies: pip3 install dnslib configparser IPy pyinstaller
# - Clone repository
# - pyinstaller dnschef.py
# - Put the contents of dist/dnschef into the "dnschef_windows.zip"
# - Upload that onto the server (/home/gitlab-runner/dnschef_windows.zip)