name: Build binaries

on:
  push:
    branches: [ master ]

jobs:

#  build-mac:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup Python
#        uses: actions/setup-python@v2
#        with: 
#          python-version: 3.8
#      - name: Configure Python
#        run: |
#          python -m pip install --upgrade pip
#          pip install dnslib configparser IPy nuitka
#      - name: Compile for Mac
#        run: |
#          python -m nuitka dnschef.py --follow-imports
#          mv dnschef.bin dnschef-mac.elf
#      - name: Upload distribution
#        uses: actions/upload-artifact@v2
#        with:
#          name: dnschef-mac
#          path: | 
#            dnschef-mac.elf
#
#  build-linux:
#    runs-on: ubuntu-18.04
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup Python
#        uses: actions/setup-python@v2
#        with: 
#          python-version: 3.8
#      - name: Configure Python
#        run: |
#          python -m pip install --upgrade pip
#          pip install dnslib configparser IPy nuitka
#      - name: Compile for Ubuntu
#        run: |
#          python -m nuitka dnschef.py --follow-imports
#          mv dnschef.bin dnschef-linux.elf
#      - name: Upload distribution
#        uses: actions/upload-artifact@v2
#        with:
#          name: dnschef-linux
#          path: | 
#            dnschef-linux.elf

  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: Download mingw
        run: |
          curl -L https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z/download -o mingw.7z
          7z x mingw.7z -r -oc:/
      - name: Configure Python
        run: |
          python -m pip install --upgrade pip
          pip install dnslib configparser IPy nuitka
      - name: Compile for Windows
        run: |
          python -m nuitka dnschef.py --follow-imports
          mv dnschef.bin dnschef-windows.exe
          ./dnschef-windows.exe
        env: 
          CC: "C:\\mingw64\\bin\\gcc.exe"
      - name: Upload distribution
        uses: actions/upload-artifact@v2
        with:
          name: dnschef-windows
          path: dnschef-windows.exe